# -*- coding: utf-8 -*-
"""Multi-Image Color Analysis & KMeans Segmentation Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcttHvO8cH9y-UW4tHzF-peOlVEF7m_F
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from google.colab import files

def analyze_image(img_rgb, image_name="", n_colors=5):
    """
    Verilen RGB görüntüyü bileşenlerine ayırır ve analiz eder:
    - Orijinal
    - RGB kanalları
    - HSV kanalları
    - Kenar tespiti (Canny)
    - Baskın renkler (KMeans)
    - Segmentasyon (KMeans sonuçları ile)
    """
    print(f"\n===== Analiz edilen görsel: {image_name} =====")

    # --- RGB Kanalları ---
    R, G, B = cv2.split(img_rgb)

    fig, axs = plt.subplots(1, 4, figsize=(16, 4))
    fig.suptitle(f"RGB Kanalları - {image_name}", fontsize=14)

    axs[0].imshow(img_rgb)
    axs[0].set_title("Orijinal")
    axs[0].axis("off")

    axs[1].imshow(R, cmap="gray")
    axs[1].set_title("R Kanalı")
    axs[1].axis("off")

    axs[2].imshow(G, cmap="gray")
    axs[2].set_title("G Kanalı")
    axs[2].axis("off")

    axs[3].imshow(B, cmap="gray")
    axs[3].set_title("B Kanalı")
    axs[3].axis("off")

    plt.tight_layout()
    plt.show()

    # --- HSV Kanalları ---
    img_hsv = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2HSV)
    H, S, V = cv2.split(img_hsv)

    fig, axs = plt.subplots(1, 4, figsize=(16, 4))
    fig.suptitle(f"HSV Kanalları - {image_name}", fontsize=14)

    axs[0].imshow(img_rgb)
    axs[0].set_title("Orijinal (RGB)")
    axs[0].axis("off")

    axs[1].imshow(H, cmap="gray")
    axs[1].set_title("Hue (Renk)")
    axs[1].axis("off")

    axs[2].imshow(S, cmap="gray")
    axs[2].set_title("Saturation (Doygunluk)")
    axs[2].axis("off")

    axs[3].imshow(V, cmap="gray")
    axs[3].set_title("Value (Parlaklık)")
    axs[3].axis("off")

    plt.tight_layout()
    plt.show()

    # --- Canny Kenar Tespiti ---
    img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(img_gray, threshold1=100, threshold2=200)

    plt.figure(figsize=(6, 6))
    plt.imshow(edges, cmap="gray")
    plt.axis("off")
    plt.title(f"Canny Kenar Tespiti - {image_name}")
    plt.show()

    # --- Baskın Renkler (KMeans) ---
    pixels = img_rgb.reshape(-1, 3)

    kmeans = KMeans(n_clusters=n_colors, random_state=42)
    kmeans.fit(pixels)

    colors = kmeans.cluster_centers_.astype(int)
    labels = kmeans.labels_

    print("Baskın renkler (RGB):")
    for i, c in enumerate(colors):
        print(f"{i+1}. renk:", c)

    plt.figure(figsize=(8, 2))
    for i, c in enumerate(colors):
        plt.subplot(1, n_colors, i+1)
        plt.imshow(np.ones((50, 50, 3), dtype=np.uint8) * c)
        plt.axis("off")
        plt.title(f"Renk {i+1}")
    plt.tight_layout()
    plt.show()

    # --- Segmentasyon ---
    segmented_pixels = colors[labels]
    segmented_img = segmented_pixels.reshape(img_rgb.shape)

    plt.figure(figsize=(6, 6))
    plt.imshow(segmented_img)
    plt.axis("off")
    plt.title(f"KMeans Segmentasyon (n_colors={n_colors}) - {image_name}")
    plt.show()

# Birden fazla görsel yükle (6 tane de olur, daha fazla da)
uploaded = files.upload()

print("Yüklenen dosyalar:")
for name in uploaded.keys():
    print("-", name)

for image_name, file_content in uploaded.items():
    # byte -> numpy array
    file_bytes = np.frombuffer(file_content, np.uint8)
    img_bgr = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

    if img_bgr is None:
        print(f"Görsel okunamadı: {image_name}")
        continue

    # BGR -> RGB
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # Orijinal görüntüyü hızlıca göster
    plt.figure(figsize=(4, 4))
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.title(f"Orijinal - {image_name}")
    plt.show()

    # Analiz fonksiyonunu çağır
    analyze_image(img_rgb, image_name=image_name, n_colors=5)