# -*- coding: utf-8 -*-
"""RhoRisk-Meriç | Web-Augmented Financial Risk LLM Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SEf6aLvxPk5AcpCFPDGF-_2hYWHMQIp
"""

# ================================
# RhoRisk-Meriç – Full Colab Pipeline (FINAL)
# Web-Augmented Financial Risk LLM (TinyLlama + LoRA + RAG + Gradio)
# ================================

# --------- [1] KURULUM ---------
!pip install -q transformers accelerate peft bitsandbytes datasets
!pip install -q langchain langchain-community faiss-cpu duckduckgo-search sentence-transformers gradio ddgs

# Kurulumdan sonra:
# Runtime → Restart runtime
# Restart sonrası bu hücreyi tekrar ÇALIŞTIRMA.
# Aşağıdaki kodları yeni hücrelere bölüp sırayla çalıştır.


# --------- [2] MODEL + TOKENIZER + LoRA + 4-BIT ---------
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model

BASE_MODEL_ID = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    device_map="auto",
    quantization_config=bnb_config
)

SYSTEM_PROMPT = (
    "You are RhoRisk-Meriç, a bilingual Turkish–English AI assistant specialized ONLY in financial risk analytics. "
    "You answer questions related to credit risk, market risk, liquidity risk, operational risk, model risk, "
    "systemic risk, Basel regulations, stress testing and financial fraud. "
    "For non-financial topics you politely redirect to financial risk topics."
)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

print("✅ RhoRisk-Meriç model + LoRA + 4-bit hazır.")


# --------- [3] TEMEL LLM CEVAP FONKSİYONU ---------
def llm_answer(prompt, max_new_tokens=256, temperature=0.7, top_p=0.9):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=top_p,
            pad_token_id=tokenizer.eos_token_id
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Hızlı test:
test_prompt = f"{SYSTEM_PROMPT}\n\nUser: Finansal risk türlerini kısaca açıklar mısın?\nAssistant:"
print(llm_answer(test_prompt)[:400])


# --------- [4] LANGCHAIN + DUCKDUCKGO + FAISS (RAG) ---------
from langchain_community.utilities import DuckDuckGoSearchAPIWrapper
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document

search = DuckDuckGoSearchAPIWrapper()
embedder = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vector_db = FAISS.from_texts(["initial"], embedder)

print("✅ LangChain RAG altyapısı hazır.")


# --------- [5] WEB’DEN BİLGİ ÇEKME ---------
def web_retrieve(query, k=3):
    results = search.results(query, max_results=8)

    texts = []
    for r in results:
        snippet = r.get("snippet", "")
        title = r.get("title", "")
        link = r.get("link", "")
        combined = f"{title}\n{snippet}\n{link}"
        texts.append(combined)

    global vector_db
    vector_db.add_texts(texts)
    docs = vector_db.similarity_search(query, k=k)
    return docs

# Test:
docs_test = web_retrieve("Basel III capital requirements overview")
print("🔎 Örnek doküman:\n", docs_test[0].page_content[:300])


# --------- [6] RAG + LLM BİRLEŞİMİ ---------
def build_rag_prompt(user_question, context_text):
    prompt = f"""
{SYSTEM_PROMPT}

Below is some external, real-world information retrieved from the web.
Use it ONLY as supporting material.

[WEB CONTEXT]
{context_text}
[END OF CONTEXT]

User question:
{user_question}

As RhoRisk-Meriç, provide a clear, professional answer focused on FINANCIAL RISK.
Answer in the same language as the question.
Assistant:
"""
    return prompt


def risk_rag_chat(user_question):
    docs = web_retrieve(user_question, k=3)
    context = "\n\n---\n\n".join([d.page_content for d in docs])

    prompt = build_rag_prompt(user_question, context)
    answer_full = llm_answer(prompt, max_new_tokens=320, temperature=0.6, top_p=0.9)

    if "Assistant:" in answer_full:
        answer = answer_full.split("Assistant:")[-1].strip()
    else:
        answer = answer_full.strip()

    return answer

# Test:
print(risk_rag_chat("Basel III kapsamında piyasa riski için getirilen başlıca yenilikler nelerdir?")[:600])


# --------- [7] GRADIO CHAT ARAYÜZÜ ---------
import gradio as gr

def chat_ui(message):
    if not message or message.strip() == "":
        return "Lütfen finansal risk ile ilgili bir soru yaz."
    return risk_rag_chat(message)

app = gr.Interface(
    fn=chat_ui,
    inputs=gr.Textbox(label="Financial Risk Question", placeholder="Örn: Basel III'e göre likidite riski nasıl ölçülür?"),
    outputs=gr.Textbox(label="RhoRisk-Meriç Answer"),
    title="RhoRisk-Meriç – Web-Augmented Financial Risk LLM",
    description="Ask about credit risk, market risk, Basel, VaR, stress testing, liquidity and fraud."
)

app.launch(share=True)


# --------- [8] LoRA FINE-TUNE İSKELETİ – KAVRAM + SENARYO TABANLI FİNANSAL RİSK Q&A ---------
from datasets import Dataset
import random

def build_training_example(user, assistant):
    text = (
        f"<|system|>\n{SYSTEM_PROMPT}\n"
        f"<|user|>\n{user}\n"
        f"<|assistant|>\n{assistant}"
    )
    return {"text": text}

# 1) ÇEKİRDEK (SEED) KAVRAM BAZLI FİNANSAL RİSK BİLGİLERİ
concept_seeds = [
    ("Kredi riski",
     "Kredi riski, borçlunun yükümlülüklerini zamanında ve tam olarak yerine getirememe ihtimalidir. "
     "Bankalar PD, LGD ve EAD modelleri, limit yönetimi, teminatlandırma ve portföy çeşitlendirmesi ile bu riski yönetir."),
    ("PD, LGD ve EAD",
     "PD temerrüt olasılığını, LGD temerrüt gerçekleştiğinde kayıp oranını, EAD ise temerrüt anındaki maruziyeti ifade eder. "
     "Beklenen kredi zararı genellikle EL = PD × LGD × EAD formülüyle hesaplanır."),
    ("Piyasa riski",
     "Piyasa riski, faiz oranları, döviz kurları, hisse senedi ve emtia fiyatlarındaki değişimlerden kaynaklanan kayıp riskidir."),
    ("VaR (Value at Risk)",
     "VaR, belirli bir zaman diliminde ve belirli bir güven seviyesinde beklenen maksimum kaybı ölçer ve piyasa riski için yaygın olarak kullanılır."),
    ("Expected Shortfall",
     "Expected Shortfall, VaR seviyesinin ötesindeki ortalama kaybı ölçer ve kuyruk riskini daha iyi yakaladığı için daha tutarlı bir risk ölçüsüdür."),
    ("Likidite riski",
     "Likidite riski, kısa vadeli yükümlülüklerin zamanında karşılanamaması riskidir. LCR ve NSFR bu riski ölçmek için kullanılır."),
    ("LCR (Likidite Karşılama Oranı)",
     "LCR, yüksek kaliteli likit varlıkların 30 günlük stres altındaki net nakit çıkışlarını karşılama kabiliyetini ölçer ve en az %100 olması hedeflenir."),
    ("NSFR (Net Stable Funding Ratio)",
     "NSFR, bir yıllık ufukta mevcut istikrarlı fonlamanın gereken istikrarlı fonlamaya oranını ölçerek, daha uzun vadeli fonlamayı teşvik eder."),
    ("Operasyonel risk",
     "Operasyonel risk, süreçler, insanlar, sistemler ve dış olaylardan kaynaklanan kayıp riskidir. Dolandırıcılık, BT arızaları ve insan hataları tipik örneklerdir."),
    ("Model riski",
     "Model riski, hatalı varsayımlar, veri sorunları veya yanlış kullanım nedeniyle modellerin yanlış sonuç üretmesi riskidir."),
    ("Sistemik risk",
     "Sistemik risk, bir kurum veya piyasadaki şokların, ağ etkileri ve bulaşma kanallarıyla finansal sistemin geneline yayılması riskidir."),
    ("Basel III",
     "Basel III, sermaye yeterliliği, kaldıraç oranı ve likidite oranlarına ilişkin küresel bankacılık standartlarını belirleyen düzenleyici çerçevedir."),
    ("FRTB (Fundamental Review of the Trading Book)",
     "FRTB, Basel III kapsamında piyasa riski sermaye gereksinimlerini yeniden tanımlayan çerçevedir; VaR yerine Expected Shortfall kullanımı öne çıkar."),
    ("IFRS 9 ve beklenen kredi zararı",
     "IFRS 9, beklenen kredi zararı (ECL) yaklaşımını getirerek, PD, LGD ve EAD'ye dayalı ileriye dönük karşılık hesaplamasını zorunlu kılar."),
    ("Stres testi",
     "Stres testi, makroekonomik veya piyasa şok senaryoları altında sermaye, likidite ve kârlılık üzerindeki etkileri ölçmek için kullanılır."),
    ("Karşı taraf kredi riski",
     "Karşı taraf kredi riski, özellikle türev işlemlerde, sözleşme süresi boyunca karşı tarafın yükümlülüklerini yerine getirememe riskidir."),
    ("Wrong-way risk",
     "Wrong-way risk, maruziyet ile karşı tarafın kredi kalitesi arasında olumsuz korelasyon olduğunda ortaya çıkar; maruziyet artarken kredi kalitesi bozulur."),
    ("Risk iştahı",
     "Risk iştahı, bir kurumun stratejik hedeflerine ulaşmak için kabul etmeye hazır olduğu toplam risk seviyesidir."),
    ("Konsantrasyon riski",
     "Konsantrasyon riski, portföyün tek bir müşteri, sektör veya ülkeye aşırı odaklanması nedeniyle çeşitlendirme etkisinin zayıflaması riskidir."),
    ("Fraud (finansal dolandırıcılık) riski",
     "Finansal dolandırıcılık riski, sahte veya yanıltıcı işlemler nedeniyle kayıp yaşanması riskidir. Anomali tespiti ve davranışsal modeller bu alanda kullanılır."),
    ("Explainable AI (XAI) ve fraud",
     "XAI, dolandırıcılık tespit modellerinde hangi özelliklerin kararı tetiklediğini açıklamaya yardımcı olur ve düzenleyici uyumu destekler."),
    ("PIT ve TTC PD",
     "PIT PD, mevcut ekonomik koşulları yansıtan temerrüt olasılığını; TTC PD ise döngü boyunca ortalama temerrüt olasılığını ifade eder."),
    ("ICAAP",
     "ICAAP, bankanın içsel sermaye yeterliliği değerlendirme sürecidir ve risk profili, strateji ve stres testlerini entegre eder.")
]

concept_question_templates = [
    "Nedir ve neden önemlidir: {topic}?",
    "{topic} kavramını teknik olarak açıklar mısın?",
    "{topic} finansal risk yönetiminde nasıl kullanılır?",
    "{topic} için tipik bir banka örneği verebilir misin?",
    "Basel çerçevesinde {topic} nasıl ele alınır?",
    "{topic} yanlış yönetilirse ne tür kayıplar oluşabilir?",
    "{topic} hangi metriklerle ölçülür veya izlenir?",
    "Risk komitesine sunum yapıyormuşsun gibi {topic} konusunu özetler misin?",
    "{topic} ile ilgili sık yapılan hatalar nelerdir?",
    "{topic} ile ilişkili diğer risk türleri hangileridir?"
]

# 2) SENARYO BAZLI SEED’LER (KRİZ, ŞOK, FRAUD, VB.)
scenario_seeds = [
    ("ani faiz artışı senaryosu",
     "Ani faiz artışı senaryosunda, sabit faizli menkul kıymetlerin değeri düşer, faiz riski artar ve uzun vade tahvil portföyleri ciddi piyasa riski taşır. "
     "Ayrıca, faiz artışlarına duyarlı sektörlerde kredi temerrütleri artabilir."),
    ("kur şoku ve devalüasyon senaryosu",
     "Kur şoku senaryosunda, döviz açık pozisyonu olan kurumlar ve döviz geliri olmayan borçlular ciddi zararlar yaşayabilir. "
     "FX riski, kredi riski ve likidite riski aynı anda tetiklenebilir."),
    ("likidite sıkışıklığı ve piyasa kuruması",
     "Likidite sıkışıklığında piyasada alıcı bulmak zorlaşır, bid-ask spread'ler açılır ve varlıkları makul fiyattan satmak güçleşir. "
     "Bu durum hem likidite hem de piyasa riskini artırır."),
    ("büyük bir bankanın iflası",
     "Sistemik öneme sahip bir bankanın iflası, karşı taraf kredi riski, güven kaybı ve mevduat çıkışları yoluyla zincirleme etki yaratabilir. "
     "Ödemeler sistemi ve finansal istikrar üzerinde ciddi etkileri olur."),
    ("yaygın bir kredi temerrüt dalgası",
     "Ekonomik resesyon veya sektör şoku sırasında geniş çaplı kredi temerrütleri yaşanabilir. "
     "Bu durumda PD'ler artar, LGD yükselir ve bankaların sermaye oranları hızla eriyebilir."),
    ("büyük bir iç dolandırıcılık vakası",
     "Büyük bir iç dolandırıcılık vakası, operasyonel riskin gerçekleşmiş bir örneğidir. "
     "Finansal kaybın yanında itibar kaybı, regülasyon cezaları ve risk kültürü sorgulaması gündeme gelir."),
    ("siber saldırı ve sistem kesintisi",
     "Siber saldırılar, operasyonel risk kapsamında ele alınır ve kritik sistemlerin durmasına, müşteri verisi ihlaline ve finansal kayıplara yol açabilir."),
    ("ülke notunun düşürülmesi (sovereign downgrade)",
     "Ülke notunun düşürülmesi, kamu borçlanma maliyetlerini artırır, bankaların devlet tahvili portföyünde değer kayıplarına ve fonlama maliyetlerinde artışa neden olabilir."),
    ("emlak balonunun patlaması",
     "Emlak balonunun patlaması, teminat değeri olarak kullanılan gayrimenkullerin fiyatını düşürür, LGD'yi artırır ve mortgage portföylerinde kredi riski sorunları yaratır."),
    ("küresel risk iştahının ani düşmesi",
     "Küresel risk iştahının ani düşmesi, gelişmekte olan ülke varlıklarından çıkışa, CDS spreadlerinde genişlemeye ve fonlama maliyetlerinde artışa yol açabilir.")
]

scenario_question_templates = [
    "{scenario} durumunda hangi ana risk türleri tetiklenir ve nasıl?",
    "{scenario} senaryosunda kredi riski nasıl etkilenir?",
    "{scenario} senaryosunda piyasa riski ve likidite riski ilişkisini açıklar mısın?",
    "{scenario} için örnek bir stres testi kurgular mısın?",
    "{scenario} yaşandığında hangi erken uyarı göstergeleri takip edilmelidir?",
    "{scenario} sonrasında sermaye yeterliliği üzerindeki etkiler nasıl analiz edilir?",
    "{scenario} vakasında risk iştahı ve limitler nasıl gözden geçirilmelidir?",
    "{scenario} karşısında hangi risk azaltma (mitigation) stratejileri uygulanabilir?",
    "{scenario} ile operasyonel ve itibar riskinin bağlantısını açıklar mısın?",
    "{scenario} senaryosunu ICAAP ve ILAAP çerçevesinde nasıl raporlarız?"
]

# 3) TÜM ÖRNEKLERİ OLUŞTUR
examples = []

# Kavram bazlı örnekler
for topic, base_answer in concept_seeds:
    for template in concept_question_templates:
        q = template.format(topic=topic)
        examples.append(build_training_example(q, base_answer))

# Senaryo bazlı örnekler
for scenario, scen_answer in scenario_seeds:
    for template in scenario_question_templates:
        q = template.format(scenario=scenario)
        examples.append(build_training_example(q, scen_answer))

random.shuffle(examples)
print("✅ Üretilen toplam eğitim örneği:", len(examples))

train_ds = Dataset.from_list(examples)

# 4) TOKENİZASYON
def tokenize_fn(batch):
    out = tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=512
    )
    out["labels"] = out["input_ids"].copy()
    return out

tokenized_train = train_ds.map(tokenize_fn, batched=True, remove_columns=["text"])

# 5) TRAINER AYARLARI (EĞİTİMİ SEN BAŞLATACAKSIN)
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="RhoRisk-Meric-lora",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=20,
    save_strategy="epoch",
    optim="paged_adamw_8bit"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
)

# 🔴 BİLEREK YOK:
# trainer.train()
# model.save_pretrained("RhoRisk-Meric-lora")
# tokenizer.save_pretrained("RhoRisk-Meric-lora")
# Bunları istersen ayrı bir hücrede sen çağırırsın.

trainer.train()
model.save_pretrained("RhoRisk-Meric-lora")
tokenizer.save_pretrained("RhoRisk-Meric-lora")